# Generated by Django 6.0.3 on 2026-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono_acudiente',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono de contacto'),
        ),
    ]
