# Generated by Django 5.2.14 on 2026-06-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_telefono_acudiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nombre_acudiente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_acudiente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_madre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre de la madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre_padre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del padre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_madre',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de la madre'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_padre',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono del padre'),
        ),
    ]
