# Generated by Django 5.2.14 on 2026-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_reemplaza_acudiente_por_padres'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre_tutor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_tutor',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono del tutor'),
        ),
    ]
