# Generated by Django 5.2.14 on 2026-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_agrega_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historial_clinico',
            field=models.TextField(blank=True, default='', verbose_name='Historial clínico'),
        ),
    ]
