# Generated by Django 5.2.14 on 2026-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_agrega_historial_clinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='escolaridad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Escolaridad'),
        ),
    ]
