# Generated by Django 5.2.14 on 2026-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_agrega_escolaridad_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='barrio',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
    ]
