# Generated by Django 5.2.14 on 2026-06-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_reemplaza_direccion_por_calle_barrio_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Dirección'),
        ),
    ]
