server {
    listen 80;
    server_name _;  # acepta cualquier IP/dominio

    client_max_body_size 10M;

    location /static/ {
        alias /home/ubuntu/fonoapp/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/fonoapp/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/fonoapp/fonoapp.sock;
        proxy_read_timeout 120;
    }
}
