# Generated by Django 6.0.3 on 2026-04-10 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='Rol')),
                ('puede_ver_pacientes', models.BooleanField(default=True, verbose_name='Ver pacientes')),
                ('puede_crear_pacientes', models.BooleanField(default=True, verbose_name='Crear pacientes')),
                ('puede_editar_pacientes', models.BooleanField(default=True, verbose_name='Editar pacientes')),
                ('puede_ver_agenda', models.BooleanField(default=True, verbose_name='Ver agenda')),
                ('puede_crear_citas', models.BooleanField(default=True, verbose_name='Crear citas')),
                ('puede_editar_citas', models.BooleanField(default=True, verbose_name='Editar citas')),
                ('puede_cancelar_citas', models.BooleanField(default=True, verbose_name='Cancelar citas')),
                ('puede_ver_usuarios', models.BooleanField(default=False, verbose_name='Ver usuarios')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Gestionar usuarios')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
