# Generated by Django 6.0.3 on 2026-04-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_telefono_acudiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(choices=[('08:00', '08:00'), ('08:40', '08:40'), ('09:20', '09:20'), ('10:00', '10:00'), ('10:40', '10:40'), ('11:20', '11:20'), ('12:00', '12:00'), ('12:40', '12:40'), ('13:20', '13:20'), ('14:00', '14:00'), ('14:40', '14:40'), ('15:20', '15:20'), ('16:00', '16:00'), ('16:40', '16:40'), ('17:20', '17:20'), ('18:00', '18:00'), ('18:40', '18:40'), ('19:20', '19:20')], max_length=5, verbose_name='Hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('fecha', 'hora')},
            },
        ),
    ]
